name: start_github

on:
  workflow_dispatch:
    inputs:
      PAYLOAD:
        description: 'Payload'
        required: false
jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: ghcr.io/faasr/github-actions-tidyverse
    env:
      SECRET_PAYLOAD: ${{ secrets.SECRET_PAYLOAD }}
      GITHUB_PAT: ${{ secrets.PAT }}
      PAYLOAD_REPO: ${{ vars.PROJECT1_PAYLOAD_REPO }}
      PAYLOAD: ${{ github.event.inputs.PAYLOAD }}
    steps:
    - name: run Rscript
      run: |
        cd /action
        Rscript faasr_start_invoke_github-actions.R
